### ISSUE TITLE
关于文字序列、字典翻译，可以看看这个

### ISSUE THREAD

**Issue by duangsuse** [itorr/nbnhhsh#1]
这是利用 ParserKt 解析器框架编写的一个示例
使用的技术为一种等价 Iterator 的输入流(`Feed`)、字典树(`TrieTree`)

划词应用就是 `onTextSelected` 和 `toast` / `showDialog` 两个 UI 逻辑，还得有一个 `translate`。如果找不到的话可以参考一下这个来实现。

```kotlin
interface Feed<T> { //<输入流
  val peek: T
  fun consume(): T
}
```

https://github.com/ParserKt/examples/blob/master/extendedSyntax/src/commonMain/kotlin/%E6%A9%99%E5%BC%8F.kt

**Comment by itorr** [comment]
感谢w 如果有类似需求需要实现会参考😝
