### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by WilliamK7** [itorr/nbnhhsh#100]
在支持的网站上会出现这样的 bug ，在网站的最底端出现
![image](https://user-images.githubusercontent.com/82304956/169443557-b5d9c3ff-da4f-41d1-842a-1b2fc38b9eff.png)

**Comment by itorr** [comment]
已修复！感谢 issues https://github.com/itorr/nbnhhsh/commit/04bc52b8eb80c42f1a242fecd914d5e1e58ff0de

**Comment by WilliamK7** [comment]
感谢作者修复
另， 希望能同步到 greasyfork 上 ，上面的反馈也是我提的，作者可以不用重复回复了
谢谢
