### ISSUE TITLE
大陆阿里云服务器丢包严重

### ISSUE THREAD

**Issue by NekoSola** [itorr/nbnhhsh#106]
在各种阿里云的大陆服务器ping lab.magiconch.com显示丢包率在70%左右
但是家用宽带ping正常

**Comment by itorr** [comment]
感谢反馈 阿里云香港是这么个问题😢 我用阿里云国内服务器 ping 也是这样

实际访问除了贵州和个别小地区运营商倒是还很流畅

最近流量不是很大，找个时间切到阿里云国内试试看

**Comment by itorr** [comment]
已经换到阿里云上海一段时间了，现在观察下来国内访问要稳定很多，虽然贵州还是不能访问（
