### ISSUE TITLE
[bug]使用本脚本时，b站网页版右侧推荐视频的封面和up主的关注、充电按钮无法加载

### ISSUE THREAD

**Issue by EuropeanWithSSR** [itorr/nbnhhsh#110]
![image](https://user-images.githubusercontent.com/39738950/211532321-9332146e-0c49-4a7f-969f-e9e7f419f72a.png)

浏览器：Cent Browser 版本 5.0.1002.295（正式版本） （64 位） (Chromium 102.0.5005.167)
脚本管理器：暴力猴 版本2.13.7

**Comment by Sabiary** [comment]
浏览器：Microsoft Edge 版本 108.0.1462.76
脚本管理器：暴力猴 版本2.13.7
遇到一样的问题

**Comment by itorr** [comment]
装了暴力猴试了一下确实重现了这个问题，导致这个问题的原因是因为 暴力猴没有对 @require 的脚本注册的变量做作用域限定😔 

```javascript 
// ==UserScript==
// @name        New script - bilibili.com
// @namespace   Violentmonkey Scripts
// @match       https://www.bilibili.com/video/BV1nW4y1V7kR/
// @grant       none
// @version     1.0
// @author      -
// @description 2023/1/10 22:50:57
// ==/UserScript==
window.Vue = 1;
```

实测我甚至只要写个这样的脚本就能干掉所有需要全局调用 Vue 变量的网站😨

想要解决这个问题可能需要调整脚本的 Vue 引入方式，当前脚本被引用的地方有写多，我要考虑下怎么调整。

临时解决方案，可以选关闭本脚本、使用线上网站，或者建议使用 Tampermonkey 对用户脚本进行管理😡

**Comment by itorr** [comment]
按照 暴力猴的文档 https://violentmonkey.github.io/api/metadata-block/#inject-into 添加了 
```选项
// @inject-into  content
```
可以尝试重新安装下脚本 https://lab.magiconch.com/nbnhhsh/nbnhhsh.user.js

**Comment by WorldlineChanger** [comment]
> 

cool，解决了

**Comment by Sabiary** [comment]
https://microsoftedge.microsoft.com/addons/detail/scriptcat/liilgpjgabokdklappibcjfablkpcekh
使用ScriptCat，也复现了这个问题
