### ISSUE TITLE
避免向服务器上传全文

### ISSUE THREAD

**Issue by andylizi** [itorr/nbnhhsh#12]
首先我要感谢作者，这个项目让我笑了一整天哈哈哈哈哈。

然后进入正题。这个脚本会把用户选择的所有内容不加筛选/处理的直接上传给后端，这使我担心隐私方面的问题。这种实现意味着只要我鼠标随手一划，或者按下了 Ctrl + A，我正在浏览的内容就会被全文发送出去。。这个念头实在有点令人不舒服XD毕竟搞技术的人，在信息安全方面免不了会更敏感一些。

我想到的解决方法：
1. 在本地就先提取出文本里的缩写，然后只向服务器上传缩写。
2. 在用户选择文本后，查询机制不要立刻触发，而是在用户按下某个快捷键/右键菜单选择了某个选项后再触发。我记得好像油猴是支持用户脚本添加右键菜单的。。？

---

另外还有一个一定程度上相关的建议，我就不单独开 issue 了。建议只在选择范围里出现了中文字符，或者符合缩写的判定（比如 `/[a-z]+/`）时才触发，避免对不相关的英文内容进行无意义的识别。

**Comment by itorr** [comment]
理解，这个问题其实考虑了蛮久没特别理想方案暂时搁置了😞

先更新一版把最基础的上传缩写内容缩减到 `/[a-z0-9]+/i` 以及选中文字是否包含需转义文字的判定。
https://github.com/itorr/nbnhhsh/commit/5e03e9d3fd5e2b191f48dffd3d0d896b6d98b55a

触发查询机制的问题我再想想😖

**Comment by MY1L** [comment]
@itorr 能否临时加一条，在选择完整链接时不触发？
例子：`https://github.com/itorr/nbnhhsh/issues/12` 划一下这个会弹出很多匹配。

**Comment by unbyte** [comment]
> 理解，这个问题其实考虑了蛮久没特别理想方案暂时搁置了😞
> 
> 先更新一版把最基础的上传缩写内容缩减到 `/[a-z0-9]+/i` 以及选中文字是否包含需转义文字的判定。
> [5e03e9d](https://github.com/itorr/nbnhhsh/commit/5e03e9d3fd5e2b191f48dffd3d0d896b6d98b55a)
> 
> 触发查询机制的问题我再想想😖

增加一步操作，能免除很多烦恼：绑定快捷键，触发后读取剪贴板并上传

**Comment by SpacelessL** [comment]
> 理解，这个问题其实考虑了蛮久没特别理想方案暂时搁置了😞
> 
> 先更新一版把最基础的上传缩写内容缩减到 `/[a-z0-9]+/i` 以及选中文字是否包含需转义文字的判定。
> [5e03e9d](https://github.com/itorr/nbnhhsh/commit/5e03e9d3fd5e2b191f48dffd3d0d896b6d98b55a)
> 
> 触发查询机制的问题我再想想😖

感觉应该根据选中长度筛选一下, 并且支持大写字母...

**Comment by itorr** [comment]
> > 理解，这个问题其实考虑了蛮久没特别理想方案暂时搁置了😞
> > 先更新一版把最基础的上传缩写内容缩减到 `/[a-z0-9]+/i` 以及选中文字是否包含需转义文字的判定。
> > [5e03e9d](https://github.com/itorr/nbnhhsh/commit/5e03e9d3fd5e2b191f48dffd3d0d896b6d98b55a)
> > 触发查询机制的问题我再想想😖
> 
> 感觉应该根据选中长度筛选一下, 并且支持大写字母...

这个是昨天后端更新时的一个bug，已经修复了
