### ISSUE TITLE
建议支持知乎

### ISSUE THREAD

**Issue by Sherlock-Holo** [itorr/nbnhhsh#14]
众所周知(?)，知乎上也有许多使用拼音缩写来代表的词语，例如
- gcd = 共产党
- mz = 民主
- gj = 国家

**Comment by Hulenkius** [comment]
你可以在脚本前头添上一行：
`// @match        *://*.zhihu.com/*`

**Comment by itorr** [comment]
默认支持知乎我想想就有点抵触，还是交给用户自行添加吧。
https://github.com/itorr/nbnhhsh#%E5%A6%82%E4%BD%95%E5%9C%A8%E6%9B%B4%E5%A4%9A%E7%BD%91%E7%AB%99%E4%B8%8A%E4%BD%BF%E7%94%A8%E8%BF%99%E4%B8%AA%E7%94%A8%E6%88%B7%E8%84%9A%E6%9C%AC
