### ISSUE TITLE
lab.magiconch.com 证书链不全

### ISSUE THREAD

**Issue by imlonghao** [itorr/nbnhhsh#16]
您好，

我在试图写一个 Telegram Bot 通过 API 来进行查询，在对接 API 的时候发现 lab.magiconch.com 证书链不全，导致无法正常发起 SSL 链接。

```
# curl https://lab.magiconch.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

https://www.ssllabs.com/ssltest/analyze.html?d=lab.magiconch.com

![image](https://user-images.githubusercontent.com/4951333/78453923-5e3f5600-76c7-11ea-9625-6801873a4d5c.png)

看起来是缺少了一个中间证书，建议使用 fullchain.cer 这个证书

**Comment by itorr** [comment]
感谢 Issues 提交。看来我一直都用错了😨 已经换成了 `fullchain.cer`

**Comment by imlonghao** [comment]
看起来没问题了。
