### ISSUE TITLE
手残给大佬来挖新坑了

### ISSUE THREAD

**Issue by samondlee** [itorr/nbnhhsh#17]
之前有个47大佬写了个POI加密一直不会调用，所以一直用TXT作为中间件在服务器上读写，也没法实现酷炫的在同一页进行加密解密的效果。

不知道大佬有没有兴趣把它完善呀呜呜呜。

仓库地址：https://github.com/samondlee/poinicoencodedecode
![preview](https://user-images.githubusercontent.com/8521327/78641276-915e3100-78e3-11ea-9b47-f8eaa72145b3.png)

**Comment by itorr** [comment]
太贰刺猿了🙅🏿‍♀️
