### ISSUE TITLE
Quicker动作（任何地方选中文字进行翻译）

### ISSUE THREAD

**Issue by cuiliang** [itorr/nbnhhsh#19]
大佬您好，我使用你的API制作了一个Quicker动作，可以在任何地方选中文字后查询。
https://getquicker.net/Sharedaction?code=db166bab-e912-4e6b-17cf-08d7dec8856a

![能不能好好说话](https://user-images.githubusercontent.com/1972649/79086454-a832d680-7d6e-11ea-827c-6b61cf0ebfa2.gif)

是否考虑提供url参数支持，这样也可以选中后直接打开网页翻译了。

另外，如果您的API不方便第三方调用，请告诉我，我把它下架掉。谢谢！

**Comment by itorr** [comment]
感谢规范 `user-agent` 的 API 调用！

支持了 URL 参数查询
https://github.com/itorr/nbnhhsh/commit/a77f8e13dd383c639e918afe3f619e7d43e7ae51

格式为 `https://lab.magiconch.com/nbnhhsh/#/text/${encodeURIComponent(text)}`
例子[https://lab.magiconch.com/nbnhhsh/#/text/%E5%A5%BD%E5%A5%BD%E8%AF%B4%E8%AF%9Dhhsh%0Abhm%0A](https://lab.magiconch.com/nbnhhsh/#/text/%E5%A5%BD%E5%A5%BD%E8%AF%B4%E8%AF%9Dhhsh%0Abhm%0A)

**Comment by cuiliang** [comment]
谢谢，已更新动作支持浏览器打开了😁。

![能不能好好说好2](https://user-images.githubusercontent.com/1972649/79092953-344ff880-7d85-11ea-9d89-b59fee2f23b8.gif)

**Comment by itorr** [comment]
在 readme 中添加了链接，感谢参与这个项目

**Comment by cuiliang** [comment]
> 在 readme 中添加了链接，感谢参与这个项目

谢谢大佬~
