### ISSUE TITLE
词库补充建议（TMD）

### ISSUE THREAD

**Issue by Windows1995** [itorr/nbnhhsh#23]
颌关节紊乱病（TMD）
参见
https://www.colgate.com.cn/oral-health/conditions/temporomandibular-disorder/what-is-temporomandibular-joint-disorder-tmj

**Comment by itorr** [comment]
参见贡献词条说明
https://github.com/itorr/nbnhhsh#%E8%B4%A1%E7%8C%AE%E8%AF%8D%E6%9D%A1
