### ISSUE TITLE
考虑对缩写进行贪婪匹配。

### ISSUE THREAD

**Issue by Butanediol** [itorr/nbnhhsh#27]
最近出现的一个问题：
`nmsl` 会被拆成 `nm` 和 `sl` 两个词组，尽管它是没有间隔的。

![BprD5HjSA9uWiXV](https://i.loli.net/2020/04/16/BprD5HjSA9uWiXV.png)

**Comment by itorr** [comment]
服务器端新增了一项拆字功能，确实部分词不适合拆分。把sl的拆分先去掉了
