### ISSUE TITLE
为 nvnhhsh写了个 Android 端

### ISSUE THREAD

**Issue by KunMinX** [itorr/nbnhhsh#29]
![](https://i.loli.net/2020/04/17/eSd7aHb5pMmFTP4.png)

在 v2ex 文末留了该仓库的链接，算是为这个仓库引流了，

https://www.v2ex.com/t/663564

android 端下载地址：

https://www.coolapk.com/apk/260094

**Comment by KunMinX** [comment]
我在 v2ex 文末留了该仓库的链接，算是为这个仓库引流了，
与此同时，android 端下载量好生凄惨 哈哈哈哈哈哈

**Comment by yichangshengwu** [comment]
要是有大佬弄个 linux 端的就好啦，
支持划词翻译的那种，
聊天软件里遇到想不出的就不用复制出来查啦
