### ISSUE TITLE
建议设置捐助页面

### ISSUE THREAD

**Issue by ibigbug** [itorr/nbnhhsh#3]
可以让更多热爱汉字的人贡献一份微薄之力

**Comment by duangsuse** [comment]
只是如果作为作者的角度来看，要设置的话可能会增加心理压力 :thinking:

**Comment by ibigbug** [comment]
> 只是如果作为作者的角度来看，要设置的话可能会增加心理压力 :thinking: 

看作者个人意愿了，本身也是自愿的。

**Comment by itorr** [comment]
这个项目最初也是我自己觉得需要才做的🤣现在最主要问题还是词条不全，补全词条才是现在对这个项目最好的帮助。（如果之后维护成本提供的时候可能确实需要考虑捐助😆
