### ISSUE TITLE
能不能支持url查询参数

### ISSUE THREAD

**Issue by SharonOlds** [itorr/nbnhhsh#37]
这样iOS就能选中后用捷径查，不用每次都切换到浏览器了٩(๑´0`๑)۶

**Comment by itorr** [comment]
目前是 URL 查询的支持的w 如果能维持可用性并且方便分享的话欢迎 pull 进README.md 


格式为 
```JavaScript
`https://lab.magiconch.com/nbnhhsh/#/text/${encodeURIComponent(text)}` 
```
[例子](https://lab.magiconch.com/nbnhhsh/#/text/%E5%A5%BD%E5%A5%BD%E8%AF%B4%E8%AF%9Dhhsh%0Abhm%0A)
