### ISSUE TITLE
DEMO网站挂了，可以提供在本地使用的词库吗

### ISSUE THREAD

**Issue by MonianHello** [itorr/nbnhhsh#40]
是否瞬移都无法访问https://lab.magiconch.com
包括之前另一个114514的DEMO也无法访问
是因为最近流量太多了吗？还是遭到了攻击
部署时不会删除掉原有的捐助二维码，请放心。

lab.magiconch.com/api/nbnhhsh/guess:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by Jonathon52306** [comment]
现在是404了诶
服务器都变成了nginx刚装好的样子

**Comment by itorr** [comment]
是遭到了攻击，现在已经恢复了。😖 现在词汇量增加了好多并且每天都在新增，本地词库方案的设计更麻烦了😞真的要实现可能要做热词冷门的区别
