### ISSUE TITLE
支持知乎么

### ISSUE THREAD

**Issue by Ppsj** [itorr/nbnhhsh#53]
知乎的轮子大佬好多黑话。
表示无能翻译。
怎么我怎么贡献数据源呢

**Comment by itorr** [comment]
可以自行添加 zhihu.com 支持 https://github.com/itorr/nbnhhsh#%E5%A6%82%E4%BD%95%E5%9C%A8%E6%9B%B4%E5%A4%9A%E7%BD%91%E7%AB%99%E4%B8%8A%E4%BD%BF%E7%94%A8%E8%BF%99%E4%B8%AA%E7%94%A8%E6%88%B7%E8%84%9A%E6%9C%AC

贡献词条
https://github.com/itorr/nbnhhsh#%E8%B4%A1%E7%8C%AE%E8%AF%8D%E6%9D%A1
