### ISSUE TITLE
能不能录个动图显示一下脚本运行后的效果

### ISSUE THREAD

**Issue by div2009** [itorr/nbnhhsh#58]
我在油猴上添加了脚本和用户运行规则以后。并没有看到有什么效果...
一般查询还是要去专门的网站上查询。
![image](https://user-images.githubusercontent.com/21057587/83388005-46aef000-a420-11ea-84f1-e9801c1177cf.png)
![测试脚本u1s1](https://user-images.githubusercontent.com/21057587/83388551-364b4500-a421-11ea-9753-5106d99ccf77.gif)

是我哪里操作不对吗？

**Comment by MooWantFree** [comment]
![image](https://user-images.githubusercontent.com/46401523/83413506-8391db80-a44e-11ea-927a-22b01cb9d4bb.png)
有适配网站范围的, 有需要得自己改一下脚本

**Comment by div2009** [comment]
看我的第一个截图，我已经修改为全网站适配了 "*"


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MooWantFree"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 晚上9:26
收件人:&nbsp;"itorr/nbnhhsh"<nbnhhsh@noreply.github.com&gt;;
抄送:&nbsp;"Everafree"<div2009@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [itorr/nbnhhsh] 能不能录个动图显示一下脚本运行后的效果 (#58)





 

 有适配网站范围的, 有需要得自己改一下脚本
