### ISSUE TITLE
能不能支持哔哩哔哩，并且上架https://greasyfork.org/zh-CN，方便用户下载升级

### ISSUE THREAD

**Issue by yinzhefuyun** [itorr/nbnhhsh#6]
能不能支持哔哩哔哩，并且上架https://greasyfork.org/zh-CN   ，方便用户下载升级，毕竟这么好的脚本很难在从github上发现，通常用户下载脚本都是去脚本的下载地

**Comment by itorr** [comment]
好！支持了哔哩哔哩、上架了 GreasyFork
https://github.com/itorr/nbnhhsh/commit/97cf4d1467ac1905519c84732d9e6664681ec030

**Comment by yinzhefuyun** [comment]
> 好！支持了哔哩哔哩、上架了 GreasyFork
> [97cf4d1](https://github.com/itorr/nbnhhsh/commit/97cf4d1467ac1905519c84732d9e6664681ec030)

谢谢大佬
