### ISSUE TITLE
API

### ISSUE THREAD

**Issue by BlueSky01st** [itorr/nbnhhsh#62]
有API可供调用吗？

**Comment by Reverier-Xu** [comment]
同求一个API (这样可以方便整理到QQ机器人中emmm)

**Comment by BlueSky01st** [comment]
我想Python调用，没有的话只能用爬虫了(不知作者是否同意……)

**Comment by h7ml** [comment]
[api](https://greasyfork.org/zh-CN/scripts/398555-%E8%83%BD%E4%B8%8D%E8%83%BD%E5%A5%BD%E5%A5%BD%E8%AF%B4%E8%AF%9D/code)地址这么大，你们居然都看不到的吗

**Comment by EricTianC** [comment]
Python已经有人写了包了[https://github.com/purofle/nbnhhsh-python](url),可以直接用

**Comment by h7ml** [comment]
> Python已经有人写了包了[https://github.com/purofle/nbnhhsh-python](url),可以直接用

链接text正确，href的地址还是本项目。

**Comment by EricTianC** [comment]
> > Python 已经有人写了包了 [https://github.com/purofle/nbnhhsh-python](url), 可以直接用
> 
> 链接 text 正确，href 的地址还是本项目。

github文本还不大熟悉，[https://github.com/purofle/nbnhhsh-python](https://github.com/purofle/nbnhhsh-python)

**Comment by xmt328** [comment]
> [api](https://greasyfork.org/zh-CN/scripts/398555-%E8%83%BD%E4%B8%8D%E8%83%BD%E5%A5%BD%E5%A5%BD%E8%AF%B4%E8%AF%9D/code)地址这么大，你们居然都看不到的吗

又不是有地址就ok了,有整理好的参数不比去看代码理解要舒服么

**Comment by Reverier-Xu** [comment]
POST 地址: `https://lab.magiconch.com/api/nbnhhsh/guess`
参数: `{"text" : "缩写文本"}` 格式为`application/json`
返回值也为`json`格式的数据:
```
[
    {
        "name": "xxx",
        "trans": ["result"]
    }
]
```
如果没有查询到对应的缩写那么有可能返回自动推断的信息:
```
[
    {
        "name": "yygqasdf",
        "inputting": [
            "阴阳怪气阿斯顿飞"
        ]
    }
]
```
如果什么都没有, 那么返回值像这样:
```
[
    {
        "name": "xxxx",
        "inputting": []
    }
]
```
