### ISSUE TITLE
提供类似于搜索引擎的查询方式

### ISSUE THREAD

**Issue by liangjiancang** [itorr/nbnhhsh#63]
比如，在地址栏 `https://lab.magiconch.com/nbnhhsh/?text=smdx` 可以在直接打开 `https://lab.magiconch.com/nbnhhsh/` 并显示查询 `smdx` 的结果。这样很多浏览器扩展可以将其当成一个搜索引擎轻松地整合使用。

**Comment by itorr** [comment]
目前是支持 URL 查询的w 如果能维持可用性并且方便分享的话欢迎 pull 进README.md

格式为

`https://lab.magiconch.com/nbnhhsh/#/text/${encodeURIComponent(text)}`
