### ISSUE TITLE
词条审核疑惑

### ISSUE THREAD

**Issue by linvon** [itorr/nbnhhsh#64]
随便打了一个 jkl ，结果里面竟然有 ‘侏儒水畜‘  ’皇杂的爹’ 这种人身攻击词，这也不是对缩写的扩展释义吧，完全就是强行攻击，这竟然也审核通过了吗。。

**Comment by itorr** [comment]
感谢反馈，已经处理

**Comment by CKylinMC** [comment]
> 感谢反馈，已经处理

![image](https://user-images.githubusercontent.com/11648014/123420322-02bff780-d5ee-11eb-8a06-006e621bc582.png)

又被加回来了，而且还多了一个...
