### ISSUE TITLE
能给知乎加一下吗

### ISSUE THREAD

**Issue by liyufeijack090706** [itorr/nbnhhsh#70]

**Comment by itorr** [comment]
请参考 [如何在更多网站上使用这个用户脚本](https://github.com/itorr/nbnhhsh#%E5%A6%82%E4%BD%95%E5%9C%A8%E6%9B%B4%E5%A4%9A%E7%BD%91%E7%AB%99%E4%B8%8A%E4%BD%BF%E7%94%A8%E8%BF%99%E4%B8%AA%E7%94%A8%E6%88%B7%E8%84%9A%E6%9C%AC)
