### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by RS-Nocsi** [itorr/nbnhhsh#77]
期待Wordpress插件版
因为我的博客就是Wordpress的awa

**Comment by itorr** [comment]
只需要按照 https://github.com/itorr/nbnhhsh#%E7%BB%99%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E6%B7%BB%E5%8A%A0%E5%88%92%E8%AF%8D%E8%BD%AC%E4%B9%89 添加即可
