### ISSUE TITLE
cdn 速度好慢，是我网络的问题吗？

### ISSUE THREAD

**Issue by Leo555** [itorr/nbnhhsh#78]
![image](https://user-images.githubusercontent.com/16870698/113704295-86182e00-970e-11eb-97ff-c86496ac5c92.png)

换了Wi-Fi和4G，都是这么慢

**Comment by Yvonne1231-Wang** [comment]
我也很慢

**Comment by itorr** [comment]
已经切换到了源站点，这个CDN确实经常抽风
