### ISSUE TITLE
可以提供一个可以直接返回结果的API接口吗

### ISSUE THREAD

**Issue by naivescrooge** [itorr/nbnhhsh#79]
可以提供一个可以直接返回结果的API接口吗

**Comment by naivescrooge** [comment]
所有可能结果以json形式返回即可

**Comment by JimmyRice** [comment]
有现成了的呀

调开发者工具，调Network

POST请求https://lab.magiconch.com/api/nbnhhsh/guess

JSON 携带一个 text 是你的缩写

希望可以帮到你XD

**Comment by Jack-bin183** [comment]
https://lab.magiconch.com/api/nbnhhsh/guess挂掉了吗？

**Comment by naivescrooge** [comment]
谢谢，很早以前就知道这个接口了，忘了关issue了
