### ISSUE TITLE
提供几个最近看到的，尤其是最后一个黑话

### ISSUE THREAD

**Issue by arsize** [itorr/nbnhhsh#84]
yyds	永远的神
blh	白莲花
u1s1	有一说一
pph	扯皮黑
srds	虽然但是	
xswl	笑死我了
dw	毒唯
ky	杠精/没眼色
xlx	小聋瞎，又聋又瞎
xtm	小透明
wwdmzzfyb	为我的莽撞自罚一杯

还有最近学到的几个：
蚌埠住了	绷不住了
四则运算工程师	++--就x自己的%牲（加加减减就成自己的畜生）

**Comment by xiaopangju** [comment]
试了一下，大多已经有了
