### ISSUE TITLE
关于提示 包含不安全内容、被多人举报，以停止访问该网页

### ISSUE THREAD

**Issue by LikeJson** [itorr/nbnhhsh#87]
腾讯日常一刀切行为
只要是 非大陆IP 统统 `包含不安全内容、被多人举报，以停止访问该网页`
打开
https://urlsec.qq.com/complain.html
提交表单即可

**Comment by xiaopangju** [comment]
顺便问一句，提交之后会有回复吗？

Yours faithfully,

Haoran Du


________________________________
From: LikeJson ***@***.***>
Sent: Saturday, July 17, 2021 5:13:29 PM
To: itorr/nbnhhsh ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [itorr/nbnhhsh] 关于提示 包含不安全内容、被多人举报，以停止访问该网页 (#87)


腾讯日常一刀切行为
只要是 非大陆IP 统统 包含不安全内容、被多人举报，以停止访问该网页
打开
https://urlsec.qq.com/complain.html
提交表单即可

―

**Comment by DevHjz** [comment]
直接发邮件解封即可，我的网站可以成功解封。
发送邮件到：`moment@tencent.com`
邮件主题：`【链接解封反馈】你的姓名 + 网站名称`
内容格式：
```
您好，
我的网站 _https://你的域名_ 被QQ以及微信封禁，经过检查，应该属于误封，网站中并无违规内容。（**类似的废话说明没有违规即可。**）
因此申请解封处理，谢谢！
```

**Comment by LikeJson** [comment]
忘记了，好像是有的

**Comment by LikeJson** [comment]
![image](https://user-images.githubusercontent.com/85022954/129999357-a8167ce4-23ab-4aff-8a8f-ab36a2eaf82f.png)
结案
