### ISSUE TITLE
能不能好好说话

### ISSUE THREAD

**Issue by kevinluo6188** [itorr/nbnhhsh#9]
nmb不应该=你妈币么

**Comment by itorr** [comment]
欢迎贡献词条 😁 

https://github.com/itorr/nbnhhsh#%E8%B4%A1%E7%8C%AE%E8%AF%8D%E6%9D%A1

**Comment by kevinluo6188** [comment]
我没有发现这个贡献的入口啊

**Comment by itorr** [comment]
@kevinluo6188 通过用户脚本选中文字或者在项目主页文本框输入之后、列表会出现对应词条，在对应词条的右上角有提交入口😊
