### ISSUE TITLE
请求添加NGA论坛

### ISSUE THREAD

**Issue by harisonkhlil** [itorr/nbnhhsh#92]
NGA也有好多看不懂的谜语人。阿西吧。

**Comment by lx865712528** [comment]
![image](https://user-images.githubusercontent.com/9069945/134369961-7a226f9f-3def-4287-8374-a0b5a93114ff.png)
可以这么改设置QvQ

**Comment by harisonkhlil** [comment]
OK

Xiao Liu ***@***.***>于2021年9月22日 周三下午11:07写道：
