### ISSUE TITLE
完善一些 Github 缩写

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [itorr/nbnhhsh#95]
| 缩写         | 全称                                            | 说明                                                 |
| :----------- | :---------------------------------------------- | :--------------------------------------------------- |
| `ACK`        | ACKnowledgement                                 | 我确认了/我接受了/我承认了                           |
| `CC`         | Carbon Copy                                     | 抄送                                                 |
| `NACK`/`NAK` | Negative ACKnowledgement                        | 我不同意                                             |
| `PTAL`       | Please Take A Look                              | 帮我看下(我的提交)                                   |
| `RFC`        | Request For Comments                            | (我觉得这个想法很好)我们来一起讨论下                 |
| `RP`         | Pull Request                                    | 提交合并代码请求                                     |
| `SGTM`       | Sounds Good To Me                               | (检查完后)没有问题                                   |
| `TBD`        | To Be Done/Defined/Discussed/Decided/Determined | 根据语境不同意义有所区别，但一般都是还没搞定的意思   |
| `TBR`        | To Be Reviewed                                  | 提示维护者进行检查                                   |
| `TL;DR`      | Too Long; Didn't Read                           | 太长懒得看(也有很多文档在做简略描述之前会写这么一句) |

**Comment by betaincao** [comment]
LGTM  look good to me.

**Comment by Zuoqiu-Yingyi** [comment]
> LGTM look good to me.

这个缩写有

**Comment by itorr** [comment]
已添加
